---
Name: ecommerce_security
Before:
  - '#app'
After:
  - '#coreconfig'
  - '#cmsextensions'
  - '#ecommerce'
---
SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\EcommerceSecurity\Model\Security\EcommerceSecurityMemberDecoration
Sunnysideup\EcommerceSecurity\Cms\SecurityCheckModelAdmin:
  managed_models:
    - Sunnysideup\EcommerceSecurity\Model\Records\EcommerceSecurityBaseClass
Sunnysideup\Ecommerce\Model\Extensions\EcommerceRole:
  admin_role_permission_codes:
    - CMS_ACCESS_SecurityCheckModelAdmin
Sunnysideup\Ecommerce\Model\Order:
  extensions:
    - Sunnysideup\EcommerceSecurity\Model\Security\EcommerceSecurityOrderDecoration
Sunnysideup\Ecommerce\Model\Process\OrderStatusLog:
  available_log_classes_array:
    - Sunnysideup\EcommerceSecurity\Model\Process\OrderStatusLogSecurityCheck
    - Sunnysideup\EcommerceSecurity\Model\Process\OrderStatusLogWhitelistCustomer
---
Name: ecommerce_security_menu
After:
  - '#coreconfig'
  - '#cmsextensions'
  - '#ecommerce'
  - '#app'
---
SilverStripe\Admin\LeftAndMain:
  menu_groups:
    Shop:
      children:
        - Sunnysideup-EcommerceSecurity-Cms-SecurityCheckModelAdmin
