---
Name: ecommerce_security
Before:
  - '#app'
After: 
  - '#coreconfig'
  - '#cmsextensions'
  - '#ecommerce'
---
SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\EcommerceSecurity\Model\Security\EcommerceSecurityMemberDecoration
Sunnysideup\EcommerceSecurity\Cms\SecurityCheck_ModelAdmin:
  managed_models:
    - Sunnysideup\EcommerceSecurity\Model\Records\EcommerceSecurityBaseClass
Sunnysideup\Ecommerce\Model\Extensions\EcommerceRole:
  admin_role_permission_codes:
    - CMS_ACCESS_SecurityCheck_ModelAdmin
Sunnysideup\Ecommerce\Model\Order:
  extensions:
    - Sunnysideup\EcommerceSecurity\Model\Security\EcommerceSecurityOrderDecoration
Sunnysideup\Ecommerce\Model\Process\OrderStatusLog:
  available_log_classes_array:
    - Sunnysideup\EcommerceSecurity\Model\Process\OrderStatusLog_SecurityCheck
    - Sunnysideup\EcommerceSecurity\Model\Process\OrderStatusLog_WhitelistCustomer
---
After: 
  - '#coreconfig'
  - '#cmsextensions'
  - '#ecommerce'
  - '#app'
Only:
  moduleexists: 'grouped-cms-menu'
---
SilverStripe\Admin\LeftAndMain:
  menu_groups:
    Shop:
      - Sunnysideup\EcommerceSecurity\Cms\SecurityCheck_ModelAdmin
