---
Name: ecommerce_security
Before:
  - 'app/*'
After:
  - 'framework/*'
  - 'cms/*'
  - 'ecommerce/*'
---

SilverStripe\Security\Member:
  extensions:
    - EcommerceSecurityMemberDecoration

SecurityCheck_ModelAdmin:
  managed_models:
    - EcommerceSecurityBaseClass


EcommerceRole:
  admin_role_permission_codes:
    - CMS_ACCESS_SecurityCheck_ModelAdmin

Order:
  extensions:
    - EcommerceSecurityOrderDecoration

OrderStatusLog:
  available_log_classes_array:
    - OrderStatusLog_SecurityCheck
    - OrderStatusLog_WhitelistCustomer


---
After:
  - 'framework/*'
  - 'cms/*'
  - 'ecommerce/*'
  - 'app/*'
Only:
  moduleexists: 'grouped-cms-menu'
---
SilverStripe\Admin\LeftAndMain:
  menu_groups:
    Shop:
      - SecurityCheck_ModelAdmin
